name: pakbazaar
description: An OLX-style marketplace starter (PakBazaar)
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.10.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.6.0
  firebase_storage: ^11.0.0
  firebase_messaging: ^14.2.0
  url_launcher: ^6.1.10
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
